### ISSUE TITLE
尾迹为相对于跟踪天体的轨迹会不会好些

### ISSUE THREAD

**Issue by SigureMo** [zkytech/Simulation-of-Star-Motion#1]
当系统稳定后，尾迹为绝对坐标系的尾迹会出现尾迹并不闭合的情况，看起来就很怪，如果可以在锁定跟踪天体后天体的尾迹也是相对于跟踪天体的，看起来会不会好些？

应该所有尾迹**序列**减去跟踪天体尾迹**序列**就行了

**Comment by zkytech** [comment]
试了一下，以恒星的视角去看，一切都是正常的，但以行星的视角去看，一切都太诡异了。待会做个功能开关吧，放在高级功能里。
![chrome_YqbN6yGEld](https://user-images.githubusercontent.com/30063898/63775574-33f80f80-c912-11e9-87de-f965ce11c7d0.png)

![TuaCBqDeT8](https://user-images.githubusercontent.com/30063898/63775891-e4661380-c912-11e9-9efe-f09cd33d96cc.gif)

**Comment by SigureMo** [comment]
嗯嗯，这样的行星参考确实很诡异:joy:，能做一个选项最好

**Comment by zkytech** [comment]
做好了，已经发布了。
